permalink: pretty
description: Clicky clicky :D
url: http://markhagethorn.nl/
author: Mark
name: Mark Hagethorn
email: mhagethorn@gmail.com
domain: http://markhagethorn.nl/
highlighter: pygments
kramdown:
  input: GFM
redcarpet:
  extensions:
    - footnotes
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
