permalink: pretty
description: Clicky clicky :D
url: http://markhagethorn.nl/
author: Mark
name: Mark Hagethorn
email: mhagethorn@gmail.com
domain: http://markhagethorn.nl/
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
